name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 15] # Java versions to test
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Validate Gradle wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Build the project
      - name: Build and Test
        run: ./gradlew check build publishToMavenLocal --stacktrace --parallel

      # (Optional) Run Auto Test Server
      # Uncomment if needed
      # - name: Run Auto Test Server
      #   run: |
      #     mkdir run
      #     echo "eula=true" >> run/eula.txt
      #     ./gradlew runAutoTestServer --stacktrace

      # Upload built artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            build/libs/patchwork-api-*.jar
            !build/libs/patchwork-api-*-*.jar
